### ISSUE TITLE
A cross-platform project fails to install a package on a non-Windows OS.

### ISSUE THREAD

**Issue by jooy2** [Eugeny/windows-native-registry#401]
Hello, thank you for providing your wonderful module.

I am facing one problem in applying this module to my solution.

I am developing a cross-platform app and I am designing my code to get the registry through this module only when it detects that it is a Windows OS.

However, when I run `npm install` on other OS (e.g. macOS), I get the following error:

```shell
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for windows-native-registry@3.2.2: wanted {"os":"win32"} (current: {"os":"darwin"})
npm ERR! notsup Valid os:  win32
npm ERR! notsup Actual os: darwin

npm ERR! A complete log of this run can be found in: /path/to/log
```

I know that this module only works on **Windows**, but I want to keep the module installed in situations where I'm forced to include it and want to branch based on the OS.

I also tried cloning this repository and removing the following from the `package.json`.

// package.json
```
 "os": [
   "win32"
  ],
```

However, on macOS, building with npm i seems to fail.

Could you please consider this? Thanks again!

Regards,

**Comment by Eugeny** [comment]
You should just add it to your `package.json`'s `optionalDependencies`, this way npm can skip it on other platforms.
